name: npm-publish

on:
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: pnpm install && pnpm run test && pnpm run build
      - run: npm publish  --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
